# 是否开启更新提醒,建议开启(Whether to turn on update alerts, recommended)
isCheckUpdate: true

# op登录时候是否发送更新提醒(Whether to send update alerts when op logs in)
isCheckUpdateToOpMsg: true

# 第一次使用请等待5分钟拉取数据
# 多久异步同步一次数据并刷新排行榜 单位秒(改动需重启生效)
task: 300

# 是否打印后台日志
msg: true

# 是否离线的时候进行同步数据(部分插件)
quitSync: false

# 要保存的下来的变量
# 例如你在config中配置了变量 %playerTitle_number%
# 需要使用 %offlinePapi_玩家名称_playerTitle_number% 就可以获取到离线版本的变量
# 玩家名使用 me 表示查询自己
papi:
  - "%playerTitle_number%"