name: OfflinePapi
main: cn.handyplus.offline.papi.OfflinePapi
version: 1.0.8
author: handy
website: https://ricedoc.handyplus.cn/wiki/OfflinePapi/
api-version: 1.13
depend: [ PlaceholderAPI ]
description: 离线变量
commands:
  offlinePapi:
    description: 离线变量
    aliases: [ opapi ]
permissions:
  offlinePapi.*:
    description: 离线变量
    children:
      offlinePapi.reload: true
      offlinePapi.init: true
      offlinePapi.delete: true
  offlinePapi.reload:
    description: 重新加载配置
    default: op
  offlinePapi.init:
    description: 初始化
    default: op
  offlinePapi.delete:
    description: 删除全部数据
    default: op